AWSTemplateFormatVersion: 2010-09-09
Resources:
  TransformExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ['logs:*']
                Resource: 'arn:aws:logs:*:*:*'
  TransformFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import traceback
          import json

          def handler(event, context):

              print(json.dumps(event))

              macro_response = {
                  "requestId": event["requestId"],
                  "status": "success"
              }
              try:
                  params = {
                      "params": event["templateParameterValues"],
                      "template": event["fragment"],
                      "account_id": event["accountId"],
                      "region": event["region"]
                  }
                  response = event["fragment"]
                  for k, v in response["Resources"].items():
                      if response["Resources"][k]["Type"] == "AWS::S3::Bucket":
                          if "Properties" in response["Resources"][k]:
                              if "AccessControl" in response["Resources"][k]["Properties"]:
                                  if response["Resources"][k]["Properties"]["AccessControl"].startswith("Public"):
                                      response["Resources"][k]["Properties"]["AccessControl"] = "Private"
                  macro_response["fragment"] = response
              except Exception as e:
                  traceback.print_exc()
                  macro_response["status"] = "failure"
                  macro_response["errorMessage"] = str(e)
              return macro_response

      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt TransformExecutionRole.Arn
  TransformFunctionPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TransformFunction.Arn
      Principal: 'cloudformation.amazonaws.com'
  Transform:
    Type: AWS::CloudFormation::Transform
    Properties:
      Name: !Sub '${AWS::AccountId}::ProtectMyBuckets'
      Description: Protects S3 Buckets
      RoutingTable:
        '*': 0_1
      Versions:
        - VersionName: 0_1
          Description: Version 0_1 of the ProtectMyBuckets transform
          FunctionName: !GetAtt TransformFunction.Arn
      ExecutionPolicy:
        Version: 2012-10-17
        Id: AllowOtherAccountPolicy
        Statement:
          - Sid: AllowExecution
            Effect: Allow
            Principal: '*'
            Action: 'cloudformation:CreateChangeSet'
            Resource: !Sub 'arn:*:cloudformation:${AWS::Region}:${AWS::AccountId}:transform/ProtectMyBuckets'
